package com.cs386p.mapforphotographers.model

import android.os.Parcelable
import com.google.firebase.Timestamp
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import kotlinx.parcelize.Parcelize
import kotlinx.serialization.Serializable

@Parcelize
data class PhotoMeta(
    // Auth information
    var ownerName: String = "",
    var ownerUid: String = "",
    var uuid : String = "",
    var byteSize : Long = 0L,
    var pictureTitle: String = "",

    var pictureDescription: String = "",
    var pictureDate: String = "",
    var pictureCamera: String = "",
    var pictureLens: String = "",
    var pictureShutterSpeed: String = "",
    var pictureFocalLength: String = "",
    var pictureAperture: String = "",
    var pictureIso: String = "",
    var pictureLat: String = "",
    var pictureLng: String = "",

    var likedBy: MutableList<String> = mutableListOf(),
    // Written on the server
    @ServerTimestamp val timeStamp: Timestamp? = null,
    // firestoreID is generated by firestore, used as primary key
    @DocumentId var firestoreID: String = ""
) : Parcelable
